# Workflow name
name: Deploy Examples to GitHub Pages

on:
  # Event for the workflow to run on
  push:
    branches:
      - 'main' # Replace with the branch you want to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Manual Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # Prepare examples for deployment
      - name: Prepare examples
        run: |
          # Create a directory for the examples build
          mkdir -p   examples-build/examples
          
          # Copy examples to the examples subdirectory
          cp -r examples/* examples-build/examples/
          
          # Copy the design system files needed by examples
          mkdir -p examples-build/examples/src
          cp -r src/* examples-build/examples/src/
      
      # Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: examples-build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 